### GET all books
GET http://localhost:3000/books HTTP/1.1

### GET a single book by ID
GET http://localhost:3000/books/B009 HTTP/1.1

### Create a new book
POST http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "_id": "B010",
    "name": "Sapiens",
    "author": "Yuval Noah Harari",
    "genreId": "G001",
    "isbn": "9780062316097",
    "isOnLoan": false,
    "activeLoanId": null
}


### DELETE a book by ID
DELETE http://localhost:3000/books/B010 HTTP/1.1

### PUT (Update) contact
PUT http://localhost:3000/books/B010 HTTP/1.1
Content-Type: application/json

{
    "name": "Sapiens",
    "author": "Yuval Noah Harari",
    "genreId": "G001",
    "isbn": "9780062316097",
    "isOnLoan": false,
    "activeLoanId": null
}