### GET all users
GET http://localhost:3000/users HTTP/1.1

### GET a single user by ID
GET http://localhost:3000/users/U009 HTTP/1.1

### Create a new user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "_id": "U011",
    "firstName": "Nicolas",
    "lastName": "Pereira",
    "phone": "555-0313",
    "email": "nicolas.pereira@example.com",
    "isPatron": true,
    "canEditCatalog": false
}


### DELETE a user by ID
DELETE http://localhost:3000/users/U011 HTTP/1.1

### PUT (Update) contact
PUT http://localhost:3000/users/U011 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Nicolas",
    "lastName": "Pereiro",
    "phone": "555-0313",
    "email": "nicolas.pereira@example.com"
}